# You are given two strings s and t.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Return the letter that was added to t.
#
#
#
# Example 1:
#
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:
#
# Input: s = "", t = "y"
# Output: "y"

def findTheDifference(s: str, t: str) -> str:
    s_sorted = sorted(s)
    t_sorted = sorted(t)
    for i in range(len(t_sorted) - 1):
        if s_sorted[i] != t_sorted[i]:
            return t_sorted[i]
    return t_sorted[-1]


print(findTheDifference(s="abcd", t="abcde"))
